/**
 * Closes the last data-retention gap: Android 12+ device-to-device transfer.
 *
 * `android.allowBackup: false` already shuts cloud backup. It is not enough on
 * its own — Android's docs, on apps targeting API 31+: *"On devices from some
 * device manufacturers, specifying `android:allowBackup="false"` disables
 * cloud-based backup and restore (such as Google Drive backups) but doesn't
 * disable device-to-device transfers for the app."* D2D is governed separately,
 * by `android:dataExtractionRules`, which is what this writes.
 *
 * **The trap this plugin exists to avoid.** The obvious implementation is an
 * empty `<device-transfer/>`, which reads like "transfer nothing". It means the
 * opposite: *"If there are no rules for a particular backup mode, such as if
 * the `<device-transfer>` section is missing, that mode is fully enabled for
 * all content."* The rules file therefore excludes all nine domains by hand.
 * See `data-extraction-rules.xml`.
 *
 * **Coverage is API 31+ only, and that is fine here.** `dataExtractionRules` is
 * ignored below Android 12; the app's minSdk is 24. On 24–30 the mechanism that
 * restores data on reinstall *is* Auto Backup, and `allowBackup="false"` shuts
 * that off completely — the split-behaviour caveat above only applies to apps
 * targeting 31+. So 24–30 is covered by `allowBackup`, and 31+ by both.
 *
 * `android/` is regenerated by `expo prebuild`, so neither the resource nor the
 * manifest attribute can be edited by hand — both are re-applied here on every
 * run.
 */
const fs = require('fs');
const path = require('path');

const { AndroidConfig, withAndroidManifest, withDangerousMod } = require('expo/config-plugins');

const RESOURCE = 'data_extraction_rules';
const SOURCE = path.join(__dirname, 'data-extraction-rules.xml');

/** Copy the rules resource into the generated project's `res/xml/`. */
const withRulesResource = (config) =>
  withDangerousMod(config, [
    'android',
    (config) => {
      const res = path.join(config.modRequest.platformProjectRoot, 'app', 'src', 'main', 'res');
      /*
       * Assert rather than mkdir -p the whole way down. If `res/` is missing we
       * are not looking at a prebuilt Android project, and silently creating
       * the tree would bury that instead of reporting it.
       */
      if (!fs.existsSync(res)) {
        throw new Error(
          `[withDataExtractionRules] expected a generated Android project at ${res}. ` +
            'Run `expo prebuild` first.'
        );
      }
      if (!fs.existsSync(SOURCE)) {
        throw new Error(`[withDataExtractionRules] missing ${SOURCE}`);
      }
      const dir = path.join(res, 'xml');
      fs.mkdirSync(dir, { recursive: true });
      // Unconditional write, which is what makes this idempotent across runs.
      fs.copyFileSync(SOURCE, path.join(dir, `${RESOURCE}.xml`));
      return config;
    },
  ]);

/** Point `<application>` at the resource. */
const withRulesAttribute = (config) =>
  withAndroidManifest(config, (config) => {
    // Throws if there is no `<application>`, or more than one.
    const application = AndroidConfig.Manifest.getMainApplicationOrThrow(config.modResults);

    /*
     * Assert the neighbouring attribute rather than trusting it.
     *
     * These rules only close the second half of the gap; `allowBackup: false`
     * closes the first and covers API 24–30 alone. If a future edit to
     * `app.json` drops it, this plugin would keep succeeding while cloud backup
     * quietly came back on — so fail prebuild loudly instead.
     */
    const allowBackup = application.$['android:allowBackup'];
    if (allowBackup !== 'false') {
      throw new Error(
        '[withDataExtractionRules] expected android:allowBackup="false" on <application>, ' +
          `found ${JSON.stringify(allowBackup)}. Set "android": { "allowBackup": false } in ` +
          'app.json — these rules do not cover API 24-30 on their own.'
      );
    }

    application.$['android:dataExtractionRules'] = `@xml/${RESOURCE}`;
    return config;
  });

module.exports = (config) => withRulesAttribute(withRulesResource(config));
