/**
 * The bundled card snapshot is build output — generated by `npm run seed` and
 * gitignored — so it is not present in a fresh checkout. Declaring it here lets
 * the app import it optionally; `loadSeedIfEmpty()` catches the resolution
 * failure and falls back to a live sync.
 */
declare module '*/seed/cards.json' {
  const seed: {
    version?: string;
    apiTotal?: number;
    count?: number;
    cards?: unknown[];
  };
  export default seed;
}
