import { existsSync, readFileSync } from 'node:fs';

import { describe, expect, it } from 'vitest';

/**
 * The bundled seed's shape, against the live schema.
 *
 * **The seed is the one path around the Zod boundary, and that is deliberate.**
 * Every network response goes through `cardSchema` at the client; the seed does
 * not, because `loadSeedIfEmpty` writes it straight through with an unchecked
 * `as NewCardRow[]` cast. The comment there justifies it correctly — the seed is
 * produced by `scripts/generate-seed.ts`, which *does* validate
 * (`cardPage.parse` at line 33) — so the data was validated, just at generation
 * rather than at load, and re-parsing 1,451 records on every cold start would
 * cost real milliseconds for a file the build produced.
 *
 * What was unguarded is the gap between those two moments. The seed is a
 * committed artefact regenerated by hand; the schema moves with migrations. If
 * they drift, the cast hides it and the rows land with `undefined` fields — the
 * exact M1 failure where 12 of 29 columns came back empty and every card in the
 * gallery rendered blank. Nothing failed; the gallery was just wrong.
 *
 * So this asserts the one thing the trust argument does not cover: **that the
 * seed on disk still has the shape the schema expects.** It is the same check
 * `schema-audit.test.ts` performs between Drizzle and the migrations, applied to
 * the third description of the same table.
 */

const SEED = 'assets/seed/cards.json';

/** Column names the `cards` table declares, read from the Drizzle schema. */
function declaredColumns(): string[] {
  const src = readFileSync('src/db/schema/cards.ts', 'utf8');
  const block = src.slice(src.indexOf('export const cards'), src.indexOf('export const syncMeta'));
  return [...block.matchAll(/(\w+):\s*(?:text|integer)\(/g)].map((m) => m[1]!);
}

describe('the bundled seed matches the schema', () => {
  /*
   * The seed is gitignored — `npm run seed` produces it and a clean checkout has
   * none. Skipping is correct there and silent passing is not, so the absence is
   * announced rather than swallowed.
   */
  const present = existsSync(SEED);

  it.runIf(present)('has every column the schema declares, and no others', () => {
    const seed = JSON.parse(readFileSync(SEED, 'utf8')) as { cards?: Record<string, unknown>[] };
    const first = seed.cards?.[0];
    expect(first, 'seed contains no cards').toBeTruthy();

    const declared = declaredColumns();
    const seeded = Object.keys(first!);

    expect(declared.filter((c) => !seeded.includes(c))).toEqual([]);
    expect(seeded.filter((c) => !declared.includes(c))).toEqual([]);
  });

  it.runIf(present)('is shaped the same all the way through, not just at row 0', () => {
    // A generator that changed mid-run, or a hand-edited file, would pass a
    // check that only ever looks at the first record.
    const seed = JSON.parse(readFileSync(SEED, 'utf8')) as { cards?: Record<string, unknown>[] };
    const cards = seed.cards ?? [];
    const shape = JSON.stringify(Object.keys(cards[0] ?? {}).sort());

    const odd = cards.findIndex((c) => JSON.stringify(Object.keys(c).sort()) !== shape);
    expect(odd, `row ${odd} has a different shape from row 0`).toBe(-1);
  });

  it.runIf(present)('carries the fields the gallery cannot render without', () => {
    // Named individually because this is the M1 bug's blast radius: these were
    // the columns that came back undefined and blanked every tile.
    const seed = JSON.parse(readFileSync(SEED, 'utf8')) as { cards?: Record<string, unknown>[] };
    const first = seed.cards![0]!;
    for (const field of ['id', 'name', 'imageUrl', 'type', 'domains', 'setId']) {
      expect(first[field], `${field} is missing from the seed`).toBeDefined();
    }
  });

  it('says so when there is no seed to check', () => {
    // Not a failure — a clean checkout has none, and the app falls back to a
    // live sync. This exists so a skipped file is visible in the run rather
    // than looking like three passes.
    if (!present) {
      console.warn(`[seed] ${SEED} not present — run \`npm run seed\`. Shape checks skipped.`);
    }
    expect(true).toBe(true);
  });
});
