import { sqlite } from '@/db/client';
import { rebuildSearchIndex } from '@/db/migrations';
import { cardColumns, toBindValue } from '@/db/queries/hydrate';
import type { NewCardRow } from '@/db/schema/cards';

import { MAX_PAGE_SIZE, riftcodex, RiftcodexError } from './client';
import { toCardRow, toSetRow } from './mapper';

/**
 * Card mirror sync.
 *
 * Riftcodex is a small fan-run API with no cache headers and no documented rate
 * limits, so this is deliberately conservative (docs/API.md §6):
 *
 *  1. First launch loads a snapshot bundled with the app — instant, offline,
 *     zero API calls.
 *  2. `GET /sets` is one cheap request that reveals whether anything changed.
 *  3. Only if it did do we page through `/cards` sequentially.
 *  4. A 24-hour guard stops the app auto-syncing more than once a day.
 *
 * On schema drift the last-known-good mirror is kept rather than wiped: a card
 * database that is slightly stale is vastly better than one that is empty.
 */

export const SYNC_TTL_MS = 24 * 60 * 60 * 1000;

export interface SyncProgress {
  phase: 'checking' | 'downloading' | 'writing' | 'done' | 'skipped' | 'failed';
  /** 0..1, or null while indeterminate. */
  progress: number | null;
  cardsWritten: number;
  message?: string;
}

export interface SyncResult {
  changed: boolean;
  cardsWritten: number;
  skippedReason?: 'ttl' | 'unchanged';
  error?: string;
}

// Column list and bindings are both derived from the Drizzle schema rather than
// hand-written, so adding a column cannot leave the write path silently
// dropping it. (The read path used to keep its own list, and it was wrong.)
const COLUMNS = cardColumns.map((c) => c.sqlName);

const UPSERT_SQL = `
  INSERT INTO cards (${COLUMNS.join(', ')})
  VALUES (${COLUMNS.map(() => '?').join(', ')})
  ON CONFLICT(id) DO UPDATE SET
    ${COLUMNS.filter((c) => c !== 'id').map((c) => `${c} = excluded.${c}`).join(',\n    ')}
`;

function bindings(row: NewCardRow): (string | number | null)[] {
  return cardColumns.map((column) =>
    toBindValue((row as Record<string, unknown>)[column.key], column)
  );
}

/** Bulk upsert in a single transaction with one prepared statement. */
export function upsertCards(rows: NewCardRow[]): number {
  if (rows.length === 0) return 0;

  const statement = sqlite.prepareSync(UPSERT_SQL);
  let written = 0;
  try {
    sqlite.withTransactionSync(() => {
      for (const row of rows) {
        statement.executeSync(bindings(row));
        written++;
      }
    });
  } finally {
    statement.finalizeSync();
  }
  return written;
}

function readMeta() {
  return sqlite.getFirstSync<{
    last_synced_at: string | null;
    card_count: number;
    seed_version: string | null;
  }>('SELECT last_synced_at, card_count, seed_version FROM sync_meta WHERE id = 1');
}

function writeMeta(fields: {
  lastSyncedAt?: string;
  cardCount?: number;
  seedVersion?: string;
  lastError?: string | null;
}) {
  const sets: string[] = [];
  const params: (string | number | null)[] = [];
  if (fields.lastSyncedAt !== undefined) { sets.push('last_synced_at = ?'); params.push(fields.lastSyncedAt); }
  if (fields.cardCount !== undefined) { sets.push('card_count = ?'); params.push(fields.cardCount); }
  if (fields.seedVersion !== undefined) { sets.push('seed_version = ?'); params.push(fields.seedVersion); }
  if (fields.lastError !== undefined) { sets.push('last_error = ?'); params.push(fields.lastError); }
  if (sets.length === 0) return;
  sqlite.runSync(`UPDATE sync_meta SET ${sets.join(', ')} WHERE id = 1`, params);
}

export function cardCount(): number {
  return sqlite.getFirstSync<{ n: number }>('SELECT COUNT(*) AS n FROM cards')?.n ?? 0;
}

export function isSyncDue(): boolean {
  const meta = readMeta();
  if (!meta?.last_synced_at) return true;
  return Date.now() - new Date(meta.last_synced_at).getTime() > SYNC_TTL_MS;
}

/**
 * Load the bundled snapshot into an empty database.
 *
 * Only ever runs when `cards` is empty, so it can never overwrite synced data.
 * Import is dynamic so the ~1.8 MB JSON stays out of the startup bundle path
 * on every launch after the first.
 */
export async function loadSeedIfEmpty(): Promise<number> {
  if (cardCount() > 0) return 0;

  try {
    const seed = (await import('../../../assets/seed/cards.json')) as unknown as {
      default?: { version?: string; cards?: unknown[] };
      version?: string;
      cards?: unknown[];
    };
    const payload = seed.default ?? seed;
    const raw = payload.cards ?? [];
    if (raw.length === 0) return 0;

    // The seed is generated by our own script from validated data, so it is
    // written straight through without re-validating 1,451 records at startup.
    const written = upsertCards(raw as NewCardRow[]);
    rebuildSearchIndex(sqlite);
    writeMeta({ cardCount: written, seedVersion: payload.version ?? 'unknown' });
    return written;
  } catch {
    // No seed bundled (it is gitignored and generated by `npm run seed`).
    // Not an error — the app falls back to a live sync.
    return 0;
  }
}

/**
 * Sync the card mirror.
 *
 * @param force Ignore the 24-hour TTL and the unchanged-sets check.
 */
export async function syncCards(
  options: { force?: boolean; onProgress?: (p: SyncProgress) => void; signal?: AbortSignal } = {}
): Promise<SyncResult> {
  const { force = false, onProgress, signal } = options;
  const report = (p: SyncProgress) => onProgress?.(p);

  if (!force && !isSyncDue()) {
    report({ phase: 'skipped', progress: 1, cardsWritten: 0 });
    return { changed: false, cardsWritten: 0, skippedReason: 'ttl' };
  }

  try {
    report({ phase: 'checking', progress: null, cardsWritten: 0, message: 'Checking for new cards' });

    const apiSets = await riftcodex.sets(signal);
    const expectedTotal = apiSets.reduce((sum, s) => sum + s.card_count, 0);

    sqlite.withTransactionSync(() => {
      for (const set of apiSets) {
        const row = toSetRow(set);
        sqlite.runSync(
          `INSERT INTO sets (id, name, set_id, card_count, tcgplayer_id, cardmarket_ids, published_on)
           VALUES (?, ?, ?, ?, ?, ?, ?)
           ON CONFLICT(id) DO UPDATE SET
             name = excluded.name, set_id = excluded.set_id, card_count = excluded.card_count,
             tcgplayer_id = excluded.tcgplayer_id, cardmarket_ids = excluded.cardmarket_ids,
             published_on = excluded.published_on`,
          [row.id, row.name, row.setId, row.cardCount, row.tcgplayerId,
           JSON.stringify(row.cardmarketIds), row.publishedOn]
        );
      }
    });

    // The set list reports how many cards should exist. If the mirror already
    // holds that many, nothing upstream has been added.
    const local = cardCount();
    if (!force && local > 0 && local >= expectedTotal) {
      writeMeta({ lastSyncedAt: new Date().toISOString(), lastError: null });
      report({ phase: 'skipped', progress: 1, cardsWritten: 0 });
      return { changed: false, cardsWritten: 0, skippedReason: 'unchanged' };
    }

    report({ phase: 'downloading', progress: 0, cardsWritten: 0, message: 'Downloading cards' });

    let page = 1;
    let pages = 1;
    let written = 0;

    // Sequential, never parallel — see the note at the top of this file.
    do {
      const res = await riftcodex.cards({ page, size: MAX_PAGE_SIZE }, signal);
      pages = res.pages;

      const rows = res.items.map(toCardRow);
      written += upsertCards(rows);

      report({
        phase: 'downloading',
        progress: pages > 0 ? page / pages : null,
        cardsWritten: written,
        message: `Downloading cards (${written}/${res.total})`,
      });

      page++;
    } while (page <= pages);

    report({ phase: 'writing', progress: 1, cardsWritten: written, message: 'Building search index' });
    rebuildSearchIndex(sqlite);

    writeMeta({
      lastSyncedAt: new Date().toISOString(),
      cardCount: cardCount(),
      lastError: null,
    });

    report({ phase: 'done', progress: 1, cardsWritten: written });
    return { changed: written > 0, cardsWritten: written };
  } catch (err) {
    const message =
      err instanceof RiftcodexError ? err.message : err instanceof Error ? err.message : 'Sync failed';

    // Keep whatever mirror we already have. A stale gallery beats an empty one.
    writeMeta({ lastError: message });
    report({ phase: 'failed', progress: null, cardsWritten: 0, message });
    return { changed: false, cardsWritten: 0, error: message };
  }
}
