import { sqlite } from '@/db/client';
import { rebuildSearchIndex } from '@/db/migrations';
import { cardColumns, toBindValue } from '@/db/queries/hydrate';
import type { NewCardRow } from '@/db/schema/cards';
import { t } from '@/i18n';

import { MAX_PAGE_SIZE, riftcodex, RiftcodexError } from './client';
import { dropStaleDuplicates, toCardRow } from './mapper';
import type { ApiCard } from './schemas';

/**
 * Card mirror sync.
 *
 * Riftcodex is a small fan-run API with no cache headers and no documented rate
 * limits, so this is deliberately conservative (docs/API.md §6):
 *
 *  1. First launch loads a snapshot bundled with the app — instant, offline,
 *     zero API calls.
 *  2. `GET /sets` is one cheap request that reveals whether anything changed.
 *  3. Only if it did do we page through `/cards` sequentially.
 *  4. A 24-hour guard stops the app auto-syncing more than once a day.
 *
 * On schema drift the last-known-good mirror is kept rather than wiped: a card
 * database that is slightly stale is vastly better than one that is empty.
 */

export const SYNC_TTL_MS = 24 * 60 * 60 * 1000;

export interface SyncProgress {
  phase: 'checking' | 'downloading' | 'writing' | 'done' | 'skipped' | 'failed';
  /** 0..1, or null while indeterminate. */
  progress: number | null;
  cardsWritten: number;
  message?: string;
}

export interface SyncResult {
  changed: boolean;
  cardsWritten: number;
  skippedReason?: 'ttl' | 'unchanged';
  error?: string;
}

// Column list and bindings are both derived from the Drizzle schema rather than
// hand-written, so adding a column cannot leave the write path silently
// dropping it. (The read path used to keep its own list, and it was wrong.)
const COLUMNS = cardColumns.map((c) => c.sqlName);

const UPSERT_SQL = `
  INSERT INTO cards (${COLUMNS.join(', ')})
  VALUES (${COLUMNS.map(() => '?').join(', ')})
  ON CONFLICT(id) DO UPDATE SET
    ${COLUMNS.filter((c) => c !== 'id').map((c) => `${c} = excluded.${c}`).join(',\n    ')}
`;

function bindings(row: NewCardRow): (string | number | null)[] {
  return cardColumns.map((column) =>
    toBindValue((row as Record<string, unknown>)[column.key], column)
  );
}

/** Bulk upsert in a single transaction with one prepared statement. */
export function upsertCards(rows: NewCardRow[]): number {
  if (rows.length === 0) return 0;

  const statement = sqlite.prepareSync(UPSERT_SQL);
  let written = 0;
  try {
    sqlite.withTransactionSync(() => {
      for (const row of rows) {
        statement.executeSync(bindings(row));
        written++;
      }
    });
  } finally {
    statement.finalizeSync();
  }
  return written;
}

function readMeta() {
  return sqlite.getFirstSync<{
    last_synced_at: string | null;
    card_count: number;
    seed_version: string | null;
  }>('SELECT last_synced_at, card_count, seed_version FROM sync_meta WHERE id = 1');
}

function writeMeta(fields: {
  lastSyncedAt?: string;
  cardCount?: number;
  seedVersion?: string;
  lastError?: string | null;
}) {
  const sets: string[] = [];
  const params: (string | number | null)[] = [];
  if (fields.lastSyncedAt !== undefined) { sets.push('last_synced_at = ?'); params.push(fields.lastSyncedAt); }
  if (fields.cardCount !== undefined) { sets.push('card_count = ?'); params.push(fields.cardCount); }
  if (fields.seedVersion !== undefined) { sets.push('seed_version = ?'); params.push(fields.seedVersion); }
  if (fields.lastError !== undefined) { sets.push('last_error = ?'); params.push(fields.lastError); }
  if (sets.length === 0) return;
  sqlite.runSync(`UPDATE sync_meta SET ${sets.join(', ')} WHERE id = 1`, params);
}

export function cardCount(): number {
  return sqlite.getFirstSync<{ n: number }>('SELECT COUNT(*) AS n FROM cards')?.n ?? 0;
}

export function isSyncDue(): boolean {
  const meta = readMeta();
  if (!meta?.last_synced_at) return true;
  return Date.now() - new Date(meta.last_synced_at).getTime() > SYNC_TTL_MS;
}

/**
 * Load the bundled snapshot into an empty database.
 *
 * Only ever runs when `cards` is empty, so it can never overwrite synced data.
 * Import is dynamic so the ~1.8 MB JSON stays out of the startup bundle path
 * on every launch after the first.
 */
export async function loadSeedIfEmpty(): Promise<number> {
  if (cardCount() > 0) return 0;

  try {
    const seed = (await import('../../../assets/seed/cards.json')) as unknown as {
      default?: { version?: string; cards?: unknown[] };
      version?: string;
      cards?: unknown[];
    };
    const payload = seed.default ?? seed;
    const raw = payload.cards ?? [];
    if (raw.length === 0) return 0;

    // The seed is generated by our own script from validated data, so it is
    // written straight through without re-validating 1,451 records at startup.
    const written = upsertCards(raw as NewCardRow[]);
    rebuildSearchIndex(sqlite);
    writeMeta({ cardCount: written, seedVersion: payload.version ?? 'unknown' });
    return written;
  } catch {
    // No seed bundled (it is gitignored and generated by `npm run seed`).
    // Not an error — the app falls back to a live sync.
    return 0;
  }
}

/**
 * Sync the card mirror.
 *
 * @param force Ignore the 24-hour TTL and the unchanged-sets check.
 */
export async function syncCards(
  options: { force?: boolean; onProgress?: (p: SyncProgress) => void; signal?: AbortSignal } = {}
): Promise<SyncResult> {
  const { force = false, onProgress, signal } = options;
  const report = (p: SyncProgress) => onProgress?.(p);

  if (!force && !isSyncDue()) {
    report({ phase: 'skipped', progress: 1, cardsWritten: 0 });
    return { changed: false, cardsWritten: 0, skippedReason: 'ttl' };
  }

  try {
    report({ phase: 'checking', progress: null, cardsWritten: 0, message: t('sync.checking') });

    const apiSets = await riftcodex.sets(signal);
    const expectedTotal = apiSets.reduce((sum, s) => sum + s.card_count, 0);

    /*
     * The response used to be mirrored into a `sets` table here. Migration 22
     * dropped it: nothing read it. The check below — the only reason this
     * request is made — uses `expectedTotal` from the response above and
     * `COUNT(*)` on `cards`, so the mirror was never consulted even by the
     * function that wrote it. `setCompletion()` likewise derives per-set
     * progress from `cards`.
     */

    // The set list reports how many cards should exist. If the mirror already
    // holds that many, nothing upstream has been added.
    const local = cardCount();
    if (!force && local > 0 && local >= expectedTotal) {
      writeMeta({ lastSyncedAt: new Date().toISOString(), lastError: null });
      report({ phase: 'skipped', progress: 1, cardsWritten: 0 });
      return { changed: false, cardsWritten: 0, skippedReason: 'unchanged' };
    }

    report({ phase: 'downloading', progress: 0, cardsWritten: 0, message: t('sync.downloading') });

    let page = 1;
    let pages = 1;
    let total = 0;
    /*
     * Collected across every page before anything is written.
     *
     * `dropStaleDuplicates` compares each row against its twin, and a pair can
     * straddle a page boundary — de-duplicating a page at a time would let the
     * split ones through. The whole response is ~1.8 MB, which is what the
     * bundled seed already holds in memory on first launch.
     */
    const collected: ApiCard[] = [];

    // Sequential, never parallel — see the note at the top of this file.
    do {
      const res = await riftcodex.cards({ page, size: MAX_PAGE_SIZE }, signal);
      pages = res.pages;
      total = res.total;
      collected.push(...res.items);

      report({
        phase: 'downloading',
        progress: pages > 0 ? page / pages : null,
        cardsWritten: 0,
        message: t('sync.downloadingCount', { done: collected.length, total: res.total }),
      });

      page++;
    } while (page <= pages);

    const written = upsertCards(dropStaleDuplicates(collected).map(toCardRow));
    report({
      phase: 'downloading',
      progress: 1,
      cardsWritten: written,
      message: t('sync.downloadingCount', { done: written, total }),
    });

    report({ phase: 'writing', progress: 1, cardsWritten: written, message: t('sync.indexing') });
    rebuildSearchIndex(sqlite);

    writeMeta({
      lastSyncedAt: new Date().toISOString(),
      cardCount: cardCount(),
      lastError: null,
    });

    report({ phase: 'done', progress: 1, cardsWritten: written });
    return { changed: written > 0, cardsWritten: written };
  } catch (err) {
    /*
     * Two messages, and separating them fixes a real leak.
     *
     * The screen used to render `err.message` raw, so a schema drift showed a
     * German user Zod's own English output — "Unexpected response shape for
     * /cards: items.0.name Expected string, received null" — in a settings
     * panel. Nothing there is actionable by a player, and none of it is
     * translated, because those strings are diagnostics.
     *
     * So the user gets a sentence, and the exception text still goes to
     * `sync_meta.last_error` where it can be read when something needs
     * diagnosing.
     */
    const detail =
      err instanceof RiftcodexError || err instanceof Error ? err.message : 'unknown error';

    // Keep whatever mirror we already have. A stale gallery beats an empty one.
    writeMeta({ lastError: detail });
    report({ phase: 'failed', progress: null, cardsWritten: 0, message: t('sync.offline') });
    return { changed: false, cardsWritten: 0, error: detail };
  }
}
