import { execFileSync } from 'node:child_process';
import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

/**
 * What the shipped Android artifact actually asks the user for.
 *
 *     npm run audit:permissions                      the built release APK
 *     npm run audit:permissions -- path/to.apk       a specific artifact
 *     npm run audit:permissions -- --manifest        the merged manifest, no APK needed
 *
 * ---
 *
 * **Why this exists as a standing check rather than a one-off audit.**
 *
 * Not one of the permissions below was written by this project. They arrive from two places, and
 * both of them move on their own:
 *
 * - **Expo's project template**, which `expo prebuild` writes into `android/app/src/main/`. Its own
 *   comment says `<!-- OPTIONAL PERMISSIONS, REMOVE WHATEVER YOU DO NOT NEED -->`, and because
 *   `android/` is regenerated every time, nobody ever does.
 * - **Library manifests**, merged in by AGP. `expo-image` brings three by way of Glide.
 *
 * So the permission set is a function of the dependency tree, and an SDK upgrade can widen it with
 * no diff in this repo to notice. A one-time audit does not survive that; an allowlist does. This
 * is the same move that made the signing pipeline trustworthy — assert the property on every build
 * rather than establish it once.
 *
 * **It reads the artifact, never the config.** `app.json` is not the manifest, and the generated
 * manifest is not the merged one. The certificate check and the data-extraction-rules check both
 * settled their questions by reading the APK back; so does this.
 */

/**
 * Every permission the release build is allowed to declare, and why.
 *
 * Adding a line here is the point at which someone decides a new permission is acceptable. Deleting
 * one is how a permission gets removed — see `plugins/withTrimmedPermissions.js`.
 */
const ALLOWED: Record<string, string> = {
  'android.permission.INTERNET':
    'card sync against the Riftcodex API, and card art from the Sanity CDN',
  'android.permission.VIBRATE':
    'expo-haptics — the result taps in the log-match sheet, and legality state changes',
  'android.permission.ACCESS_NETWORK_STATE':
    'expo-image, via Glide: restarts failed image requests when connectivity returns',
  'android.permission.READ_EXTERNAL_STORAGE':
    "expo-image and expo-file-system; capped at maxSdkVersion 32, so inert on Android 13+. Kept " +
    'deliberately: Glide declares it for its local cache path and a regression could only be ' +
    'disproved on an API 24-32 device',
  'android.permission.WRITE_EXTERNAL_STORAGE':
    'expo-file-system; capped at maxSdkVersion 32, kept for the same reason as the read one',
  'DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION':
    'generated by AndroidX from the applicationId, signature-level and self-granted; guards its ' +
    'own dynamically registered receivers',
};

/**
 * Permissions that must **not** appear, with the reason they were removed.
 *
 * Listed separately from "not in ALLOWED" on purpose: this asserts that a specific past decision
 * still holds, so a regression reports what was undone rather than only that something is new.
 */
const REMOVED: Record<string, string> = {
  'android.permission.SYSTEM_ALERT_WINDOW':
    'draw-over-other-apps. No overlay feature exists; it came from Expo\'s optional-permission ' +
    'template block. Removed by plugins/withTrimmedPermissions.js',
};

const args = process.argv.slice(2);
const manifestMode = args.includes('--manifest');
const explicitPath = args.find((a) => !a.startsWith('--'));

/** The AndroidX permission is namespaced by applicationId; compare on the suffix. */
const normalise = (name: string) =>
  name.endsWith('DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION')
    ? 'DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION'
    : name;

function fromManifest(): string[] {
  const base = join('android', 'app', 'build', 'intermediates', 'merged_manifest', 'release');
  if (!existsSync(base)) {
    fail(`no merged manifest at ${base}. Build first: cd android && ./gradlew processReleaseMainManifest`);
  }
  const dir = readdirSync(base)[0];
  if (!dir) fail(`${base} exists but is empty. Rebuild the manifest.`);
  const file = join(base, dir, 'AndroidManifest.xml');
  const xml = readFileSync(file, 'utf8');
  console.log(`source: ${file}\n`);
  return [...xml.matchAll(/<uses-permission[^>]*android:name="([^"]*)"/g)].flatMap((m) =>
    m[1] ? [m[1]] : []
  );
}

function fromApk(apk: string): string[] {
  const sdk = process.env.ANDROID_HOME ?? join(process.env.LOCALAPPDATA ?? '', 'Android', 'Sdk');
  const tools = join(sdk, 'build-tools');
  if (!existsSync(tools)) fail(`no Android build-tools under ${tools}. Set ANDROID_HOME.`);
  const newest = readdirSync(tools).sort().reverse()[0];
  if (!newest) fail(`no build-tools versions installed under ${tools}.`);
  const aapt2 = join(tools, newest, process.platform === 'win32' ? 'aapt2.exe' : 'aapt2');
  const out = execFileSync(aapt2, ['dump', 'permissions', apk], { encoding: 'utf8' });
  console.log(`source: ${apk}\n`);
  return [...out.matchAll(/^uses-permission: name='([^']*)'/gm)].flatMap((m) => (m[1] ? [m[1]] : []));
}

function fail(message: string): never {
  console.error(`\n  FAIL  ${message}\n`);
  process.exit(1);
}

function defaultApk(): string {
  const built = join('android', 'app', 'build', 'outputs', 'apk', 'release', 'app-release.apk');
  if (existsSync(built)) return built;
  const staged = readdirSync('.').filter((f) => f.endsWith('.apk')).sort().reverse()[0];
  if (staged) return staged;
  return fail('no release APK found. Build one, or pass a path, or use --manifest.');
}

const declared = [...new Set((manifestMode ? fromManifest() : fromApk(explicitPath ?? defaultApk())).map(normalise))].sort();

const unexpected = declared.filter((p) => !(p in ALLOWED));
const resurrected = declared.filter((p) => p in REMOVED);
const missing = Object.keys(ALLOWED).filter((p) => !declared.includes(p));

for (const p of declared) {
  const mark = p in ALLOWED ? 'ok  ' : 'NEW ';
  console.log(`  ${mark} ${p}`);
  if (p in ALLOWED) console.log(`        ${ALLOWED[p]}`);
}

console.log();

if (resurrected.length) {
  console.error('  A permission that was deliberately removed is back:');
  for (const p of resurrected) console.error(`    ${p}\n      removed because: ${REMOVED[p]}`);
}
if (unexpected.length) {
  console.error('  Permissions not in the allowlist:');
  for (const p of unexpected) console.error(`    ${p}`);
  console.error('\n  Each one is a decision, not a formality. Trace it with the merger blame report');
  console.error('  (android/app/build/outputs/logs/manifest-merger-release-report.txt), decide');
  console.error('  whether the app needs it, then either add it to ALLOWED with a reason or');
  console.error('  remove it in plugins/withTrimmedPermissions.js.');
}
if (missing.length) {
  console.error('  Allowlisted permissions that are no longer declared:');
  for (const p of missing) console.error(`    ${p}`);
  console.error('\n  Not necessarily a fault — a dependency may have dropped it. Confirm the');
  console.error('  feature still works, then delete the line from ALLOWED.');
}

if (resurrected.length || unexpected.length || missing.length) process.exit(1);

console.log(`  ${declared.length} permissions, all accounted for.`);
